web:
  image: cmelion/generator-ng2-webpack:latest
  volumes:
    - ./README.md:/home/yeoman/client/README.md
    - ./package.json:/home/yeoman/client/package.json
    - ./src:/home/yeoman/client/src
    - ./api:/home/yeoman/client/api
  ports:
    - "2368:2368"
    - "3000:3000"